/*
 * indexify-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.12
 * Contact: support@tensorlake.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::applications::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationRequests {
    #[serde(
        rename = "next_cursor",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub next_cursor: Option<Option<String>>,
    #[serde(
        rename = "prev_cursor",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub prev_cursor: Option<Option<String>>,
    #[serde(rename = "requests")]
    pub requests: Vec<models::ShallowRequest>,
}

impl ApplicationRequests {
    pub fn new(requests: Vec<models::ShallowRequest>) -> ApplicationRequests {
        ApplicationRequests {
            next_cursor: None,
            prev_cursor: None,
            requests,
        }
    }
}
