/*
 * indexify-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.12
 * Contact: support@tensorlake.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::applications::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Application {
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "entrypoint")]
    pub entrypoint: Box<models::EntryPointManifest>,
    #[serde(rename = "functions")]
    pub functions: std::collections::HashMap<String, models::ApplicationFunction>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "namespace")]
    pub namespace: String,
    #[serde(rename = "tags")]
    pub tags: std::collections::HashMap<String, String>,
    #[serde(rename = "tombstoned", skip_serializing_if = "Option::is_none")]
    pub tombstoned: Option<bool>,
    #[serde(rename = "version")]
    pub version: String,
}

impl Application {
    pub fn new(
        description: String,
        entrypoint: models::EntryPointManifest,
        functions: std::collections::HashMap<String, models::ApplicationFunction>,
        name: String,
        namespace: String,
        tags: std::collections::HashMap<String, String>,
        version: String,
    ) -> Application {
        Application {
            created_at: None,
            description,
            entrypoint: Box::new(entrypoint),
            functions,
            name,
            namespace,
            tags,
            tombstoned: None,
            version,
        }
    }
}
