/*
 * indexify-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.12
 * Contact: support@tensorlake.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::applications::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationFunction {
    #[serde(rename = "cache_key", skip_serializing_if = "Option::is_none")]
    pub cache_key: Option<String>,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(
        rename = "initialization_timeout_sec",
        skip_serializing_if = "Option::is_none"
    )]
    pub initialization_timeout_sec: Option<i32>,
    #[serde(rename = "max_concurrency")]
    pub max_concurrency: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Vec<models::ParameterMetadata>>,
    #[serde(rename = "placement_constraints")]
    pub placement_constraints: Box<models::PlacementConstraints>,
    #[serde(rename = "resources")]
    pub resources: Box<models::FunctionResources>,
    #[serde(rename = "retry_policy")]
    pub retry_policy: Box<models::NodeRetryPolicy>,
    #[serde(
        rename = "return_type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub return_type: Option<Option<serde_json::Value>>,
    #[serde(rename = "secret_names")]
    pub secret_names: Vec<String>,
    #[serde(rename = "timeout_sec")]
    pub timeout_sec: i32,
}

impl ApplicationFunction {
    pub fn new(
        description: String,
        max_concurrency: i32,
        name: String,
        placement_constraints: models::PlacementConstraints,
        resources: models::FunctionResources,
        retry_policy: models::NodeRetryPolicy,
        secret_names: Vec<String>,
        timeout_sec: i32,
    ) -> ApplicationFunction {
        ApplicationFunction {
            cache_key: None,
            description,
            initialization_timeout_sec: None,
            max_concurrency,
            name,
            parameters: None,
            placement_constraints: Box::new(placement_constraints),
            resources: Box::new(resources),
            retry_policy: Box::new(retry_policy),
            return_type: None,
            secret_names,
            timeout_sec,
        }
    }
}
