/*
 * indexify-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.12
 * Contact: support@tensorlake.ai
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateNamespace {
    #[serde(
        rename = "blob_storage_bucket",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub blob_storage_bucket: Option<Option<String>>,
    #[serde(
        rename = "blob_storage_region",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub blob_storage_region: Option<Option<String>>,
    #[serde(rename = "name")]
    pub name: String,
}

impl CreateNamespace {
    pub fn new(name: String) -> CreateNamespace {
        CreateNamespace {
            blob_storage_bucket: None,
            blob_storage_region: None,
            name,
        }
    }
}
