/*
 * indexify-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.12
 * Contact: support@tensorlake.ai
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntryPointManifest {
    #[serde(rename = "function_name")]
    pub function_name: String,
    #[serde(rename = "input_serializer")]
    pub input_serializer: String,
    #[serde(rename = "output_serializer")]
    pub output_serializer: String,
    #[serde(rename = "output_type_hints_base64")]
    pub output_type_hints_base64: String,
}

impl EntryPointManifest {
    pub fn new(
        function_name: String,
        input_serializer: String,
        output_serializer: String,
        output_type_hints_base64: String,
    ) -> EntryPointManifest {
        EntryPointManifest {
            function_name,
            input_serializer,
            output_serializer,
            output_type_hints_base64,
        }
    }
}
