/*
 * indexify-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.12
 * Contact: support@tensorlake.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::applications::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecutorAllocations {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "executor_id")]
    pub executor_id: String,
    #[serde(rename = "function_executors")]
    pub function_executors: Vec<models::FnExecutor>,
}

impl ExecutorAllocations {
    pub fn new(
        count: i32,
        executor_id: String,
        function_executors: Vec<models::FnExecutor>,
    ) -> ExecutorAllocations {
        ExecutorAllocations {
            count,
            executor_id,
            function_executors,
        }
    }
}
