/*
 * indexify-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.12
 * Contact: support@tensorlake.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::applications::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecutorMetadata {
    #[serde(rename = "addr")]
    pub addr: String,
    #[serde(rename = "clock")]
    pub clock: i64,
    #[serde(rename = "executor_version")]
    pub executor_version: String,
    #[serde(rename = "free_resources")]
    pub free_resources: Box<models::HostResources>,
    #[serde(
        rename = "function_allowlist",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub function_allowlist: Option<Option<Vec<models::FunctionAllowlist>>>,
    #[serde(rename = "function_executors")]
    pub function_executors: Vec<models::FunctionExecutorMetadata>,
    #[serde(rename = "host_resources")]
    pub host_resources: Box<models::HostResources>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "labels")]
    pub labels: std::collections::HashMap<String, String>,
    #[serde(rename = "server_only_function_executors")]
    pub server_only_function_executors: Vec<models::FunctionExecutorMetadata>,
    #[serde(rename = "state")]
    pub state: String,
    #[serde(rename = "state_hash")]
    pub state_hash: String,
    #[serde(rename = "tombstoned")]
    pub tombstoned: bool,
}

impl ExecutorMetadata {
    pub fn new(
        addr: String,
        clock: i64,
        executor_version: String,
        free_resources: models::HostResources,
        function_executors: Vec<models::FunctionExecutorMetadata>,
        host_resources: models::HostResources,
        id: String,
        labels: std::collections::HashMap<String, String>,
        server_only_function_executors: Vec<models::FunctionExecutorMetadata>,
        state: String,
        state_hash: String,
        tombstoned: bool,
    ) -> ExecutorMetadata {
        ExecutorMetadata {
            addr,
            clock,
            executor_version,
            free_resources: Box::new(free_resources),
            function_allowlist: None,
            function_executors,
            host_resources: Box::new(host_resources),
            id,
            labels,
            server_only_function_executors,
            state,
            state_hash,
            tombstoned,
        }
    }
}
