/*
 * indexify-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.12
 * Contact: support@tensorlake.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::applications::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FnExecutor {
    #[serde(rename = "allocations")]
    pub allocations: Vec<models::Allocation>,
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "desired_state")]
    pub desired_state: String,
    #[serde(rename = "fn_uri")]
    pub fn_uri: String,
    #[serde(rename = "function_executor_id")]
    pub function_executor_id: String,
    #[serde(rename = "state")]
    pub state: String,
}

impl FnExecutor {
    pub fn new(
        allocations: Vec<models::Allocation>,
        count: i32,
        desired_state: String,
        fn_uri: String,
        function_executor_id: String,
        state: String,
    ) -> FnExecutor {
        FnExecutor {
            allocations,
            count,
            desired_state,
            fn_uri,
            function_executor_id,
            state,
        }
    }
}
