/*
 * indexify-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.12
 * Contact: support@tensorlake.ai
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionExecutorMetadata {
    #[serde(rename = "application_name")]
    pub application_name: String,
    #[serde(rename = "desired_state")]
    pub desired_state: String,
    #[serde(rename = "function_name")]
    pub function_name: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "max_concurrency")]
    pub max_concurrency: i32,
    #[serde(rename = "namespace")]
    pub namespace: String,
    #[serde(rename = "state")]
    pub state: String,
    #[serde(rename = "version")]
    pub version: String,
}

impl FunctionExecutorMetadata {
    pub fn new(
        application_name: String,
        desired_state: String,
        function_name: String,
        id: String,
        max_concurrency: i32,
        namespace: String,
        state: String,
        version: String,
    ) -> FunctionExecutorMetadata {
        FunctionExecutorMetadata {
            application_name,
            desired_state,
            function_name,
            id,
            max_concurrency,
            namespace,
            state,
            version,
        }
    }
}
