/*
 * indexify-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.12
 * Contact: support@tensorlake.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::applications::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Function {
    #[serde(rename = "cache_key", skip_serializing_if = "Option::is_none")]
    pub cache_key: Option<String>,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "fn_name")]
    pub fn_name: String,
    #[serde(
        rename = "initialization_timeout_sec",
        skip_serializing_if = "Option::is_none"
    )]
    pub initialization_timeout_sec: Option<i32>,
    #[serde(rename = "input_encoder", skip_serializing_if = "Option::is_none")]
    pub input_encoder: Option<String>,
    #[serde(rename = "max_concurrency", skip_serializing_if = "Option::is_none")]
    pub max_concurrency: Option<i32>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "output_encoder", skip_serializing_if = "Option::is_none")]
    pub output_encoder: Option<String>,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Vec<models::ParameterMetadata>>,
    #[serde(
        rename = "placement_constraints",
        skip_serializing_if = "Option::is_none"
    )]
    pub placement_constraints: Option<Box<models::PlacementConstraints>>,
    #[serde(rename = "resources", skip_serializing_if = "Option::is_none")]
    pub resources: Option<Box<models::FunctionResources>>,
    #[serde(rename = "retry_policy", skip_serializing_if = "Option::is_none")]
    pub retry_policy: Option<Box<models::NodeRetryPolicy>>,
    #[serde(
        rename = "return_type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub return_type: Option<Option<serde_json::Value>>,
    #[serde(rename = "secret_names", skip_serializing_if = "Option::is_none")]
    pub secret_names: Option<Vec<String>>,
    #[serde(rename = "timeout_sec", skip_serializing_if = "Option::is_none")]
    pub timeout_sec: Option<i32>,
}

impl Function {
    pub fn new(description: String, fn_name: String, name: String) -> Function {
        Function {
            cache_key: None,
            description,
            fn_name,
            initialization_timeout_sec: None,
            input_encoder: None,
            max_concurrency: None,
            name,
            output_encoder: None,
            parameters: None,
            placement_constraints: None,
            resources: None,
            retry_policy: None,
            return_type: None,
            secret_names: None,
            timeout_sec: None,
        }
    }
}
