/*
 * indexify-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.12
 * Contact: support@tensorlake.ai
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GpuResources {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "model")]
    pub model: String,
}

impl GpuResources {
    pub fn new(count: i32, model: String) -> GpuResources {
        GpuResources { count, model }
    }
}
