/*
 * indexify-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.12
 * Contact: support@tensorlake.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::applications::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostResources {
    #[serde(rename = "cpu_count")]
    pub cpu_count: i32,
    #[serde(rename = "disk_bytes")]
    pub disk_bytes: i64,
    #[serde(
        rename = "gpu",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub gpu: Option<Option<Box<models::GpuResources>>>,
    #[serde(rename = "memory_bytes")]
    pub memory_bytes: i64,
}

impl HostResources {
    pub fn new(cpu_count: i32, disk_bytes: i64, memory_bytes: i64) -> HostResources {
        HostResources {
            cpu_count,
            disk_bytes,
            gpu: None,
            memory_bytes,
        }
    }
}
