/*
 * indexify-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.12
 * Contact: support@tensorlake.ai
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexifyApiError {
    #[serde(rename = "message")]
    pub message: String,
}

impl IndexifyApiError {
    pub fn new(message: String) -> IndexifyApiError {
        IndexifyApiError { message }
    }
}
