/*
 * indexify-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.12
 * Contact: support@tensorlake.ai
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Namespace {
    #[serde(
        rename = "blob_storage_bucket",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub blob_storage_bucket: Option<Option<String>>,
    #[serde(rename = "created_at")]
    pub created_at: i64,
    #[serde(rename = "name")]
    pub name: String,
}

impl Namespace {
    pub fn new(created_at: i64, name: String) -> Namespace {
        Namespace {
            blob_storage_bucket: None,
            created_at,
            name,
        }
    }
}
