/*
 * indexify-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.12
 * Contact: support@tensorlake.ai
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParameterMetadata {
    #[serde(rename = "data_type", deserialize_with = "Option::deserialize")]
    pub data_type: Option<serde_json::Value>,
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "required")]
    pub required: bool,
}

impl ParameterMetadata {
    pub fn new(
        data_type: Option<serde_json::Value>,
        name: String,
        required: bool,
    ) -> ParameterMetadata {
        ParameterMetadata {
            data_type,
            description: None,
            name,
            required,
        }
    }
}
