/*
 * indexify-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.12
 * Contact: support@tensorlake.ai
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlacementConstraints {
    /// List of label filter expressions in the format \"key=value\", \"key!=value\", etc.
    #[serde(rename = "filter_expressions", skip_serializing_if = "Option::is_none")]
    pub filter_expressions: Option<Vec<String>>,
}

impl PlacementConstraints {
    pub fn new() -> PlacementConstraints {
        PlacementConstraints {
            filter_expressions: None,
        }
    }
}
