/*
 * indexify-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.12
 * Contact: support@tensorlake.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::applications::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RequestOutcome {
    String(String),
    RequestOutcomeOneOf(Box<models::RequestOutcomeOneOf>),
}

impl Default for RequestOutcome {
    fn default() -> Self {
        Self::String(Default::default())
    }
}
