/*
 * indexify-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.12
 * Contact: support@tensorlake.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::applications::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequestOutcomeOneOf {
    #[serde(rename = "failure")]
    pub failure: models::RequestFailureReason,
}

impl RequestOutcomeOneOf {
    pub fn new(failure: models::RequestFailureReason) -> RequestOutcomeOneOf {
        RequestOutcomeOneOf { failure }
    }
}
