/*
 * indexify-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.12
 * Contact: support@tensorlake.ai
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequestError {
    #[serde(rename = "function_name")]
    pub function_name: String,
    #[serde(rename = "message")]
    pub message: String,
}

impl RequestError {
    pub fn new(function_name: String, message: String) -> RequestError {
        RequestError {
            function_name,
            message,
        }
    }
}
