/*
 * indexify-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.12
 * Contact: support@tensorlake.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::applications::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Request {
    #[serde(rename = "application_version")]
    pub application_version: String,
    #[serde(rename = "created_at")]
    pub created_at: i32,
    #[serde(rename = "function_runs")]
    pub function_runs: Vec<models::FunctionRun>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(
        rename = "outcome",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub outcome: Option<Option<Box<models::RequestOutcome>>>,
    #[serde(
        rename = "request_error",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub request_error: Option<Option<Box<models::RequestError>>>,
}

impl Request {
    pub fn new(
        application_version: String,
        created_at: i32,
        function_runs: Vec<models::FunctionRun>,
        id: String,
    ) -> Request {
        Request {
            application_version,
            created_at,
            function_runs,
            id,
            outcome: None,
            request_error: None,
        }
    }
}
