/*
 * indexify-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.12
 * Contact: support@tensorlake.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::applications::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StateChangesResponse {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "state_changes")]
    pub state_changes: Vec<models::StateChange>,
}

impl StateChangesResponse {
    pub fn new(count: i32, state_changes: Vec<models::StateChange>) -> StateChangesResponse {
        StateChangesResponse {
            count,
            state_changes,
        }
    }
}
