/*
 * indexify-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.12
 * Contact: support@tensorlake.ai
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StateChange {
    #[serde(
        rename = "application",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub application: Option<Option<String>>,
    #[serde(rename = "change_type")]
    pub change_type: String,
    #[serde(rename = "created_at")]
    pub created_at: i64,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(
        rename = "namespace",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub namespace: Option<Option<String>>,
    #[serde(rename = "object_id")]
    pub object_id: String,
    #[serde(
        rename = "request",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub request: Option<Option<String>>,
}

impl StateChange {
    pub fn new(change_type: String, created_at: i64, id: String, object_id: String) -> StateChange {
        StateChange {
            application: None,
            change_type,
            created_at,
            id,
            namespace: None,
            object_id,
            request: None,
        }
    }
}
