/*
 * indexify-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.12
 * Contact: support@tensorlake.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::applications::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnallocatedFunctionRuns {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "function_runs")]
    pub function_runs: Vec<models::FunctionRun>,
}

impl UnallocatedFunctionRuns {
    pub fn new(count: i32, function_runs: Vec<models::FunctionRun>) -> UnallocatedFunctionRuns {
        UnallocatedFunctionRuns {
            count,
            function_runs,
        }
    }
}
